// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sywoshbxdaypnnhwatug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5d29zaGJ4ZGF5cG5uaHdhdHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDg4NjgsImV4cCI6MjA3MTk4NDg2OH0.bL5I-cHYiEuLFnH--z6vIuHnhOE63Dn-OQYGUMCuqjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});